admin/src/web/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired


class LoginForm(FlaskForm):
    """
        Formulario de inicio de sesión.
    """
    email_username = StringField("Usuario", description="Ingrese su email o nombre de usuario",validators=[InputRequired()])
    password = PasswordField("Contraseña", description="Ingrese su contraseña", validators=[InputRequired()])
    # remember = BooleanField("Recordarme")

admin/src/web/controllers/authentication/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, Response, jsonify
from src.core.models import user as Users
from src.web.forms import login_form as Forms
from src.web.helpers import auth
from src.web.oauth import oauth as OAuth
from src.core.models import user_institution

auth_blueprint = Blueprint("auth", __name__, url_prefix="/login")

@auth_blueprint.get("/")
def login():
    return render_template("login/login.html", form=Forms.LoginForm())

@auth_blueprint.post("/authenticate")
def authenticate():
    """
        Autenticacion de usuario a traves de login normal mediante username/email y contraseña.
    """    
    params = request.form
    user = Users.check_auth_user(params["email_username"], params["password"])
    
    if not user:
        flash("Email/Nombre de usuario o contraseña incorrectos", "error")
        return redirect(url_for("auth.login"))
        
    return redirect(url_for("auth.init_sesion_user", email_username=params["email_username"]))

@auth_blueprint.post("/update-actual-institution")
def update_actual_institution():
    """
        Actualiza la institucion actual del usuario logueado
    """
    
    id = request.json['institution_id']
    session['user']['actual_institution'] = id
    session['user']['layout'] = auth.render_layout(user_institution.get_role_id_by_user_and_institution(id, session['user']['id']))
    data = {
        "url": url_for('home.index')
    }
    return jsonify(data)

@auth_blueprint.get("/logout")
def logout():
    """
        Cierre la sesión del usuario
    """
    if session.get("user"):
        del session["user"]
        session.clear()
    else:
        flash("No existe una sesión iniciada", "info")
        
    return redirect(url_for("auth.login"))

@auth_blueprint.get("/init-sesion-user/<email_username>")
def init_sesion_user(email_username):
    """
        Inicializa la sesion del usuario
    """
    user = Users.find_user(email_username)
    
    if user:
        if not Users.check_state_user(user):
            flash("El usuario no está activo o no está confirmado", "error")
            return redirect(url_for("auth.login"))
        
        institution_role = Users.get_first_institution_rol(user)
        if institution_role is None:
            session["user"] = {
                "id": user.id,
                "email": user.email,
                "username": user.username,
                "institutions": [],
                "actual_institution": None,
                "role": None,
                "layout": auth.render_layout(0)
            }
        else:   
            session["user"] = {
                "id": user.id,
                "email": user.email,
                "username": user.username,
                "institutions": [i.institution for i in Users.get_institutions_by_userID(user.id)],
                "actual_institution": institution_role[0],
                "role": institution_role[1],
                "layout": auth.render_layout(institution_role[1])
            }
        
        return redirect(url_for("home.index"))
    else:
        flash("El usuario no está registrado", "error")
        return redirect(url_for("auth.login"))


@auth_blueprint.route("/login-google")
def login_google():
    """
        Autenticacion de usuario a traves de google cloud
    """
    redirect_uri = url_for('auth.login_google_callback', _external=True)
    
    return OAuth.google.authorize_redirect(redirect_uri)

@auth_blueprint.route("/google-callback")
def login_google_callback():
    """
        URI de callback de google cloud
    """
    token = OAuth.google.authorize_access_token()
    user = token['userinfo']

    return redirect(url_for("auth.init_sesion_user", email_username=user["email"]))

admin/src/web/templates/login/login.html
{% extends "layout.html" %}

{% block title %} Iniciar sesión {% endblock %}

{% block content %}

  {% block main %}

    {% block nav %} {% endblock %}
    {% block aside %} {% endblock %}

    <section class="flex flex-col md:flex-row h-screen items-center">
        <div class="bg-indigo-600 hidden lg:block w-full md:w-1/2 xl:w-2/3 h-screen ">
          <img src="/static/img/background.png" alt="" class="w-full h-full object-cover">
        </div>
        <div class="bg-white w-full md:max-w-md lg:max-w-full md:mx-auto md:mx-0 md:w-1/2 xl:w-1/3 h-screen px-6 lg:px-16 xl:px-12 flex items-center justify-center">
          <div class="w-full h-100">
            <div class="flex items-center justify-center">
                <a href="https://cidepint.ing.unlp.edu.ar/" class="flex ml-2 ">
                    <img src="/static/img/cidepint-logo.png" class="h-8 mr-3" alt="Cidepint-logo" />
                    <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">
                      CIDEPINT 
                    </span>
                </a>
            </div>
            <h1 class="text-xl md:text-2xl font-bold leading-tight mt-12">Iniciar sesión</h1>
            <form class="mt-6" action="{{ url_for('auth.authenticate') }}" method="POST">
              {% for input in form %}
                  <div class="mt-4">
                      {{ input.label(
                          class="block text-gray-700"
                      ) }}
                      {% if input.id == "password" %}
                        <div class="relative">
                          {{ input(
                              class="block w-full px-4 py-3 rounded-lg placeholder-gray-600 transition duration-300 bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-indigo-50 focus:outline-none",
                              placeholder=input.description) 
                          }}
                          <div class="absolute inset-y-0 end-0 flex items-center pe-3 cursor-pointer">
                            <svg id="eye-show" class="eye w-5 h-5 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
                              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1.933 10.909A4.357 4.357 0 0 1 1 9c0-1 4-6 9-6m7.6 3.8A5.068 5.068 0 0 1 19 9c0 1-3 6-9 6-.314 0-.62-.014-.918-.04M2 17 18 1m-5 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                            </svg>
                            <svg id="eye-hidde" class="eye w-5 h-5 hidden text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 14">
                              <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                <path d="M10 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                                <path d="M10 13c4.97 0 9-2.686 9-6s-4.03-6-9-6-9 2.686-9 6 4.03 6 9 6Z"/>
                              </g>
                            </svg>
                          </div>
                        </div>
                      {% else %}
                        {{ input(
                            class="w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border placeholder-gray-600 transition duration-300 focus:border-blue-500 focus:bg-indigo-50 focus:outline-none",
                            placeholder=input.description) 
                        }}
                      {% endif %}
                  </div>
              {% endfor %}

              <div class="text-right my-4">
                <a class="text-sm font-semibold cursor-pointer text-gray-700 hover:text-blue-700 focus:text-blue-700">
                  ¿Olvidaste tu contraseña?
                </a>
              </div>
              {{ Flash.flash_login() }}
              <button type="submit" class="w-full block bg-indigo-600 hover:bg-indigo-700 focus:bg-indigo-800 text-white font-semibold rounded-lg px-4 py-3 mt-6">
                Iniciar sesión
              </button>
            </form>
            <hr class="my-6 border-gray-300 w-full">
            <a href="{{ url_for('auth.login_google') }}">
              <button type="button" class="w-full block bg-white hover:bg-gray-100 focus:bg-gray-100 text-gray-900 font-semibold rounded-lg px-4 py-3 border border-gray-300">
                <div class="flex items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="w-6 h-6" viewBox="0 0 48 48"><defs><path id="a" d="M44.5 20H24v8.5h11.8C34.7 33.9 30.1 37 24 37c-7.2 0-13-5.8-13-13s5.8-13 13-13c3.1 0 5.9 1.1 8.1 2.9l6.4-6.4C34.6 4.1 29.6 2 24 2 11.8 2 2 11.8 2 24s9.8 22 22 22c11 0 21-8 21-22 0-1.3-.2-2.7-.5-4z"/></defs><clipPath id="b"><use xlink:href="#a" overflow="visible"/></clipPath><path clip-path="url(#b)" fill="#FBBC05" d="M0 37V11l17 13z"/><path clip-path="url(#b)" fill="#EA4335" d="M0 11l17 13 7-6.1L48 14V0H0z"/><path clip-path="url(#b)" fill="#34A853" d="M0 37l30-23 7.9 1L48 0v48H0z"/><path clip-path="url(#b)" fill="#4285F4" d="M48 48L17 24l-4-3 35-10z"/></svg>
                  <span class="ml-4">Iniciar sesión con Google</span>
                </div>
              </button>
            </a>
            <p class="mt-8 text-center">¿Necesitas una cuenta?
              <a href="{{ url_for('users.sign_up') }}" class="text-blue-500 hover:text-blue-700 font-semibold">Registrate aquí</a>
            </p>
            <hr class="my-6 border-gray-400 w-full">
            <a href="https://grupo10.proyecto2023.linti.unlp.edu.ar/login" target="_blank">
              <button type="button" class="w-full py-2 mb-3 text-sm font-bold leading-none text-white transition duration-300 rounded-2xl hover:bg-violet-600 focus:ring-4 focus:ring-violet-200 bg-violet-500"
              >
                Clientes
              </button>
            </a>
          </div>
        </div>
    </section>
  {% endblock %}
  
{% endblock %}

{% block javascript %}
  {{ super() }}
  <script>
    const eyeShow = document.getElementById('eye-show');
    const eyeHidde = document.getElementById('eye-hidde');
    const password = document.getElementById('password');
    eyeShow.addEventListener('click', () => showPassword());
    eyeHidde.addEventListener('click', () => showPassword());
    function showPassword(){
      if (password.type === 'password') {
        password.type = 'text';
        eyeShow.classList.add('hidden');
        eyeHidde.classList.remove('hidden');
      } else {
        password.type = 'password';
        eyeShow.classList.remove('hidden');
        eyeHidde.classList.add('hidden');
      }
    }
  </script>
{% endblock %}